<?php

use Omnipro\Omniprovincias\Block\System\Config\CityDelete;

/** @var CityDelete $block */

$controller = $block->getCustomUrl();
echo $block->getButtonHtml();
?>

<div id="modal_parent_delete_city"></div>

<script type="text/javascript">
    (function() {
        require(["jquery", "Magento_Ui/js/modal/modal"], function($, modal) {
            $(document).ready(function($) {
                var delete_button = $("#city_delete");
                $(delete_button).on('click', function(e) {
                    var selected_country = $('#omniprovincias_cities_installed_countries_city option:selected');

                    if (selected_country.val()) {

                        $.get(`<?= $block->getCustomUrl(); ?>country/${selected_country.val()}`);

                        addedRegion($("#omniprovincias_cities_installed_countries_city option:selected").text(), country_select.val());
                        removedRegion();

                        createModal({
                            type: 'popup',
                            responsive: true,
                            innerScroll: true,
                            buttons: [{
                                text: $.mage.__('Continue'),
                                class: 'regionsLoaded',
                                click: function() {
                                    this.closeModal();
                                }
                            }]
                        }, modal, "#modal_parent_delete_city");
                    }
                })
            });

            /**
             * Add country to the list of Cities that have regions.
             * @param {string} text
             * @param {string} value
             */
            function addedRegion(text, value) {
                var element = document.getElementById('omniprovincias_cities_installed_countries_city');
                var div = $('#modal_parent_delete_city');
                div.append(document.createTextNode(`Cities for ${text} have been deleted successfully.`))
            }

            /**
             * Remove country from the list of Cities without regions.
             * @return {boolean}
             */
            function removedRegion() {
                var element = document.getElementById('omniprovincias_cities_city_country');
                element.remove(element.selectedIndex);
                return true;
            }

            /**
             * Create modal with custom options
             * @param {object} options Options for modal from Magento modal
             * @param modal Modal default type from Magento
             * @param {string} parent Id or class of the parent container
             */
            function createModal(options = {}, modal, parent) {
                modal(options, $(parent));
                $(parent).modal("openModal");
            }
        });
    })();
</script>